/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author Whoop
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    private ControladorPrincipal control;
    private Modelo modelo;

    public VistaPrincipal(Modelo aThis) {
        initComponents();
        modelo = aThis;
        capturarEventos();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGro = new javax.swing.JPanel();
        contenido = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        arbolCerezo = new javax.swing.JLabel();
        agregarB = new javax.swing.JButton();
        eliminarB = new javax.swing.JButton();
        valorUsu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        limpiarB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        backGro.setBackground(new java.awt.Color(254, 227, 242));
        backGro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenido.setBackground(new java.awt.Color(255, 241, 246));
        contenido.setMaximumSize(new java.awt.Dimension(1000, 400));
        contenido.setMinimumSize(new java.awt.Dimension(1000, 400));
        contenido.setPreferredSize(new java.awt.Dimension(1000, 400));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        backGro.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 1110, 400));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Brush Script MT", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Árboles AVL");
        backGro.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        arbolCerezo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arbolCerezo.jpg"))); // NOI18N
        arbolCerezo.setText("jLabel1");
        backGro.add(arbolCerezo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 500));

        agregarB.setBackground(new java.awt.Color(204, 130, 29));
        agregarB.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        agregarB.setForeground(new java.awt.Color(255, 255, 255));
        agregarB.setText("Agregar");
        agregarB.setBorder(null);
        agregarB.setBorderPainted(false);
        agregarB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agregarB.setFocusPainted(false);
        agregarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBActionPerformed(evt);
            }
        });
        backGro.add(agregarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 130, 40));

        eliminarB.setBackground(new java.awt.Color(205, 131, 29));
        eliminarB.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        eliminarB.setForeground(new java.awt.Color(255, 255, 255));
        eliminarB.setText("Eliminar");
        eliminarB.setBorder(null);
        eliminarB.setBorderPainted(false);
        eliminarB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eliminarB.setFocusPainted(false);
        backGro.add(eliminarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 130, 40));

        valorUsu.setBackground(new java.awt.Color(255, 228, 243));
        valorUsu.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        valorUsu.setForeground(new java.awt.Color(0, 0, 0));
        valorUsu.setText("Ingrese el dato");
        valorUsu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        valorUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valorUsuMousePressed(evt);
            }
        });
        valorUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorUsuActionPerformed(evt);
            }
        });
        backGro.add(valorUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 24, 180, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        backGro.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 210, 10));

        limpiarB.setBackground(new java.awt.Color(205, 131, 29));
        limpiarB.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        limpiarB.setForeground(new java.awt.Color(255, 255, 255));
        limpiarB.setText("Limpiar");
        limpiarB.setBorder(null);
        limpiarB.setBorderPainted(false);
        limpiarB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        limpiarB.setFocusPainted(false);
        backGro.add(limpiarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 20, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backGro, javax.swing.GroupLayout.PREFERRED_SIZE, 1520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorUsuActionPerformed

    private void agregarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarBActionPerformed

    private void valorUsuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorUsuMousePressed
        valorUsu.setText("");
    }//GEN-LAST:event_valorUsuMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarB;
    private javax.swing.JLabel arbolCerezo;
    private javax.swing.JPanel backGro;
    private javax.swing.JPanel contenido;
    private javax.swing.JButton eliminarB;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton limpiarB;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField valorUsu;
    // End of variables declaration//GEN-END:variables
private void capturarEventos() {
        agregarB.addActionListener(getControl());
        eliminarB.addActionListener(getControl());
        limpiarB.addActionListener(getControl());
    }

    public JTextField getValorUsu() {
        return valorUsu;
    }

    public ControladorPrincipal getControl() {
        if (control == null) {
            control = new ControladorPrincipal(this);
        }
        return control;
    }

    public Modelo getModelo() {
        return modelo;
    }

    public void dibujarArbol(Lienzo panel) {
        Lienzo lienzo = panel;
        lienzo.setBackground(new Color(255, 241, 246));
        lienzo.setSize(1110, 400);
        lienzo.setLocation(0, 0);
        contenido.removeAll();
        contenido.add(lienzo, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }
}
